# Generated by Django 3.2 on 2021-04-27 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='post_news')),
                ('Description', models.TextField()),
                ('link', models.TextField(default='#')),
            ],
        ),
        migrations.CreateModel(
            name='ImageNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_news/details')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_posts.postnews')),
            ],
        ),
    ]
